
name: Content Upload
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a content report, please search for the behaviour in the existing issues. 
        
        ---
        
        Thank you for taking the time to file a this report. To address this issue as fast as possible, we need some information.
  - type: input
  id: title
  attributes:
    label: Tittle of the document
    description: Please insert here the title of the document.
  validations:
    required: true
- type: input
  id: metadata
  attributes:
    label: Metadata
    description: Please insert here, if available, the metadata url of the document.
  validations:
    required: false
- type: input
  id: url
  attributes:
    label: url
    description: Please provide the url or other identifier for the document.
  validations:
    required: true
